output_dir: "results/"
replicates: 100
seed: 12345
seq_len: 200

gorilla_nodels: ['GorillaNull', 'GorillaGhost', 'GorillaGhostWorst', 'GorillaNullWorst']

ms_exec: "ext/msdir/ms"
skovhmm_exec_filter: "ext/SkovHMM/FiltervariantsNOancestral.py"
skovhmm_exec_train: "ext/SkovHMM/Train.py"
skovhmm_exec_decode: "ext/SkovHMM/Decode.py"
skovhmm_exec_env: "config/SkovHMM/env.yaml"
sprime_exec: "ext/SPrime/sprime.jar"
