# Mon 25 Jul 2022 11:01:46 CEST
# check pvals for proportion of overlapping bp: comparison b/n empirical & random reps per scenario

## module load gcc/6.3.0 openssl/1.0.2q R/4.0.1
load("/scratch/devel/hpawar/admix/overlap.s*.skov/overlap.random.regions.pval.20jul22",verbose=T) # check this **
# generated using scripts -   /scratch/devel/hpawar/admix/sstar/scripts/simul_postabc/downstream/overlap.random.regions.20jul22.R
# called by - /scratch/devel/hpawar/admix/sstar/scripts/simul_postabc/downstream/overlap.random.regions.4may22.arr


# will need to go through script, b.c unsure if this is what i was expecting for the output..

#str(random_p)
#List of 4
# $ :List of 3
#  ..$ :List of 2
#  .. ..$ : num [1:100, 1] 0.134 0.129 0.131 0.132 0.145 ...
#  .. ..$ : num 0

# ie has output the means of each rep for random proportions generated by the function process_randomintersect
# but has not calculated p vals - after running interactively, it seems the p vals were indeed calculated, but all gave 0, ie non of the random reps had a higher proportion of overlappin bp than the empirical data

#-----------------------------------------------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------------------------------------------

# run through relevant functions of R script interactively -
    # /scratch/devel/hpawar/admix/sstar/scripts/simul_postabc/downstream/overlap.random.regions.20jul22.R

# empirical vals for the mean overlap

recalc_empirical_mean<-function(scen,skov_version){
overlap40kb_gbb<-list()
pt_estimate<-list()
for (ind in (1:length(scen))) {
overlap40kb_gbb[[ind]]<-intersect_function(scen[[ind]],skov_version)[[2]]
pt_estimate[[ind]]<-mean(overlap40kb_gbb[[ind]][,1])}
return(pt_estimate)
}


emp_mean_all_comp<-cbind(recalc_empirical_mean(scen_GBB,autosomes_sk_gbb),
recalc_empirical_mean(scen_GBB,autosomes_40sk_gbb),
recalc_empirical_mean(scen_GBG,autosomes_sk_gbg),
recalc_empirical_mean(scen_GBG,autosomes_40sk_gbg))

# proportion of overlapping bp for each scenario (4) & for each s* CI (3)
#> emp_mean_all_comp
#     [,1]      [,2]      [,3]      [,4]     
#[1,] 0.6424558 0.6810105 0.5561079 0.5874836
#[2,] 0.5116104 0.5458979 0.4183923 0.4435774
#[3,] 0.4215718 0.4511147 0.3377909 0.3589834

#-----------------------------------------------------------------------------------------------------------------------

#random_p[[4]][[3]][[1]] # scenario 4, 3rd confidence interval, mean vals per rep

# adapt this function, b.c already have the mean vals per replicate
#process_p_fun<-function(scen,emp,ver) {
#ran_sk_gbb2<-c()
#for (j in (1:length(scen[[ver]]))) { ran_sk_gbb2[j]<-mean(scen[[ver]][[j]]) }
#pres<-as.data.frame(table(ran_sk_gbb2>=emp[[ver]])/length(ran_sk_gbb2))
#out<-as.numeric(as.character(pres[which(pres[,1]==T),2]))
#return(out)
#}



#as.data.frame(table(random_p[[4]][[3]][[1]] >= emp_mean_all_comp[,4][3]) / length(random_p[[4]][[3]][[1]]))

# random_p[[4]][[3]][[1]][ which(random_p[[4]][[3]][[1]] > 0.05), ]
# [1] 0.05417470 0.05838330 0.05390201 0.05253115 0.05018593 0.05188763
# [7] 0.05353817 0.05006949 0.05166577 0.05254257 0.05300058 0.05089687
#[13] 0.05437748 0.05059624 0.05379760 0.05613648 0.05429357 0.05008115
#[19] 0.05007747

# length( random_p[[4]][[3]][[1]][ which(random_p[[4]][[3]][[1]] > 0.05), ])/100
#[1] 0.19

# think this should be the way to go ?


calc_p_fun<-function(scen,sstar_ver){
out <- length( random_p[[scen]][[sstar_ver]][[1]][ which(random_p[[scen]][[sstar_ver]][[1]] >= emp_mean_all_comp[,scen][sstar_ver]), ])/100
return(out)
}


# for all scernarios (gbb, gbg, gbb.40, gbg.40)

hold_j<-c()
for (j in (1:ncol(emp_mean_all_comp))) { 
per_ci<-c()
for (i in (1:nrow(emp_mean_all_comp))) { 
per_ci[[i]]<-calc_p_fun(j,i)
}
ids<-do.call(rbind,per_ci)
hold_j[[j]]<-ids
}

# ie none of the random reps have higher mean proportion overlapping htan the empirical - same as was output in the R object "/scratch/devel/hpawar/admix/overlap.s*.skov/overlap.random.regions.pval.20jul22"
> hold_j
[[1]]
     [,1]
[1,]    0
[2,]    0
[3,]    0

[[2]]
     [,1]
[1,]    0
[2,]    0
[3,]    0

[[3]]
     [,1]
[1,]    0
[2,]    0
[3,]    0

[[4]]
     [,1]
[1,]    0
[2,]    0
[3,]    0